[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
workspace = false

[tasks.clean-all]
script_runner = "@shell"
script = '''
rm -rf target
rm -rf Cargo.lock
rm -rf packages/wasm/pkg
rm -rf project/dist
rm -rf project/src/pkg
'''
workspace = false

[tasks.build-wasm]
script_runner = "@shell"
script = '''
cd packages/wasm
wasm-pack build --target web
'''
workspace = false

[tasks.build-wasm-release]
script_runner = "@shell"
script = '''
cd packages/wasm
wasm-pack build --release --target web
'''
workspace = false

[tasks.cp-wasm]
script_runner = "@shell"
script = '''
cp -r packages/wasm/pkg project/src
'''
workspace = false
dependencies = ["build-wasm"]

[tasks.npm-install]
script_runner = "@shell"
script = '''
cd project
npm install
'''
workspace = false

[tasks.run-web]
script_runner = "@shell"
script = '''
cd project
npm run dev
'''
workspace = false
dependencies = ["cp-wasm"]

[tasks.build-web]
script_runner = "@shell"
script = '''
cd project
npm run build
'''
workspace = false