[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = "z"

[dependencies]
image = "0.24.3"
halo2_proofs = { version = "0.2.0", default-features = false }
once_cell = { version = "1.16.0", default-features = false }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
